### PR TITLE
Changes to support building on Windows 

### PR DESCRIPTION
**Pull request by mwcraig**
This fixes (almost) all of the compilation issues. The only one that still comes up is that `stdint.h` isn't included with the free version of the MS compiler used to build python 2.7. One more reason to switch to python 3.5!

### CODE REVIEW

**Comment by cmccully** [comment]
Thanks for looking at this. Is there a way around the stdint.h problem for windows? If there isn't a good fix, then I will merge this for now and we can look at fixing 2.7 on Windows later.

**Comment by mwcraig** [comment]
My "fix" was to manually copy `stdint.h` from the MSVC 2015 compiler (which includes it) to the include directory for MSVC 2009 (used to compile python 2.7, doesn't have `stdint.h`).

I think the only fix is to either provide a link to the file (though I haven't found a link directly to it) or to make a known issue for it in the docs and explain how to work around it.

Path of least pain, by far, for Windows users is to use anaconda and install astroscrappy from the astropy conda channel with:

`conda install -c astropy astroscrappy`

**Comment by cmccully** [comment]
Ok. I will merge this. We should probably make a known issue about this in the documentation.

**Comment by cmccully** [comment]
@mwcraig I tried to merge this, but it failed the Travis CI. Do you mind taking a look. I have never seen this type of failure.

**Comment by mwcraig** [comment]
@cmccully -- weird. Could you try restarting the build to see if it is a one-off problem? Can't see why it would be, but it had built fine on the PR....

**Comment by cmccully** [comment]
@mwcraig I reran the test and it seemed to work. Very strange. Guess we shouldn't lose sleep over this. Everything should be merged in and ready to go. I will release a minor version shortly.

**Comment by mwcraig** [comment]
:+1:

**Pull request merged**
