### PR TITLE
Remove astropy-helpers

### PR DESCRIPTION
**Pull request by saimn**
This PR applies changes from the package template, following APE 17:
https://docs.astropy.org/projects/package-template/en/latest/ape17.html
Quite a number of changes, but mostly simplifying the package structure. 
Things to note:
- tests are now run with `tox`, and `setup.py` should no more be used directly.
- I replaced appveyor by a Travis job.
- With this some older PRs and issues can be closed: #42 #43 #44
- Build dependencies (cython, numpy) are now installed automatically when running `pip install` so I think that `.c` files should no more be included in the sdist (this would avoid issues when the c files must be re-generated for new Python/Numpy releases), but I'm not sure if APE 17 recommends something about this.
- I think the `astroscrappy*.so` file is not built with OpenMP, and this was already the case before because it is cythonized automatically, and not declared in the setup_package. I will have a look later.

### CODE REVIEW

**Comment by saimn** [comment]
As mentioned above, the `astroscrappy` module is not compiled with the OpenMP flags. This is already the case on master:
```
❯ ldd ./astroscrappy/astroscrappy.cpython-38-x86_64-linux-gnu.so
	linux-vdso.so.1 (0x00007ffff5995000)
	libpthread.so.0 => /home/simon/.linuxbrew/lib/libpthread.so.0 (0x00007f5409cde000)
	libc.so.6 => /home/simon/.linuxbrew/lib/libc.so.6 (0x00007f5409b40000)
	/home/simon/.linuxbrew/Cellar/glibc/2.23/lib64/ld-linux-x86-64.so.2 (0x00007f5409d50000)

❯ ldd ./astroscrappy/utils/image_utils.cpython-38-x86_64-linux-gnu.so
	linux-vdso.so.1 (0x00007ffda4f96000)
	libgomp.so.1 => /home/simon/.linuxbrew/lib/libgomp.so.1 (0x00007fdea2a6f000)
	libpthread.so.0 => /home/simon/.linuxbrew/lib/libpthread.so.0 (0x00007fdea2a50000)
	libc.so.6 => /home/simon/.linuxbrew/lib/libc.so.6 (0x00007fdea28b1000)
	libdl.so.2 => /home/simon/.linuxbrew/lib/libdl.so.2 (0x00007fdea28ac000)
	/home/simon/.linuxbrew/Cellar/glibc/2.23/lib64/ld-linux-x86-64.so.2 (0x00007fdea2caa000)

❯ ldd ./astroscrappy/utils/median_utils.cpython-38-x86_64-linux-gnu.so
	linux-vdso.so.1 (0x00007ffdb9b57000)
	libgomp.so.1 => /home/simon/.linuxbrew/lib/libgomp.so.1 (0x00007fcb7796c000)
	libpthread.so.0 => /home/simon/.linuxbrew/lib/libpthread.so.0 (0x00007fcb7794d000)
	libc.so.6 => /home/simon/.linuxbrew/lib/libc.so.6 (0x00007fcb777ae000)
	libdl.so.2 => /home/simon/.linuxbrew/lib/libdl.so.2 (0x00007fcb777a9000)
	/home/simon/.linuxbrew/Cellar/glibc/2.23/lib64/ld-linux-x86-64.so.2 (0x00007fcb77bb2000)
```
This is because the extension is created automatically by astropy-helpers/extension-helpers, and would be solved by adding another `setup_package.py` file to setup the correct flags.

**Comment by cmccully** [comment]
Overall, I think this looks great. A couple of things to think about are below:

- The c files were originally included because it was recommended by pypi. Is that no longer the case? This was also in response to #6, so we should make sure this fixes that issue as well.

- Originally, in setup.py we tried to automatically detect if openmp was available on the system. I like having the option to compile with openmp, so can you comment on if this option is still available?

- It's strange that the coverage report is not showing up here. Any ideas? We also originally had an issue that coveralls was not reporting the test coverage for the cython files (which is basically everything of use). Does this fix that as well?

**Comment by saimn** [comment]
>    The c files were originally included because it was recommended by pypi. Is that no longer the case? This was also in response to #6, so we should make sure this fixes that issue as well.

Since it is now easier to have build dependencies (with the `pyproject.toml` file), it is recommended not to include the .c files generated by cython. This way, it would be easier to install from sources with a newer version of cython if needed (e.g. for newer versions of Python which sometimes require some changes on Cython side).
For #6 I'm not sure what the problem was but yes I think this would be solved (it seems this was due to an issue in astropy-helpers).

>    Originally, in setup.py we tried to automatically detect if openmp was available on the system. I like having the option to compile with openmp, so can you comment on if this option is still available?

Yes, I just replaced your custom code by `extension_helpers.add_openmp_flags_if_available` which is doing the same: 
https://github.com/astropy/extension-helpers/blob/f5a3f6236796bc03349bb60ed5a5c419c66bdccd/extension_helpers/_openmp_helpers.py#L232

>    It's strange that the coverage report is not showing up here. Any ideas? 

Is there a coverage report with coveralls ? Astropy and many projects switched to codecov, which has the reports and a nicer UI,.

> We also originally had an issue that coveralls was not reporting the test coverage for the cython files (which is basically everything of use). Does this fix that as well?

No sadly, I saw the issues related to this, but last time I tried with another project I never managed to get coverage report for Cython files. Astropy used to have coverage for c files (not cython), but that seems broken.

**Comment by cmccully** [comment]
Ok. This sounds reasonable. What do we need to get things into codecov? We should make a note (an issue maybe) that the coverage report is still not quite right, but we don't need that solve that in this pr.

**Comment by saimn** [comment]
I may have a solution for the coverage:
```
----------- coverage: platform linux, python 3.8.3-final-0 -----------
Name                                  Stmts   Miss  Cover
---------------------------------------------------------
astroscrappy/__init__.py                  5      0   100%
astroscrappy/astroscrappy.pyx           209     96    54%
astroscrappy/utils/__init__.py            4      0   100%
astroscrappy/utils/image_utils.pyx       62      6    90%
astroscrappy/utils/median_utils.pyx     106     16    85%
---------------------------------------------------------
TOTAL                                   386    118    69%
```
I need to check a few more things, and maybe I can put later in another PR (to avoid accumulating too many changes) ?

**Comment by saimn** [comment]
For codecov you need to activate their app in the Github settings. I think it is already activated in the astropy org, and I'm sure if you need to activate it at the repo level as well.

**Comment by saimn** [comment]
It seems to be already activated: https://codecov.io/gh/astropy/astroscrappy
So I think we just need to replace coveralls by codecov in the travis config.

**Pull request merged**
